name: mintora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  video_player: ^2.9.5
  chewie: ^1.11.3
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.14.3
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mintora.png
    - assets/12.jpg
    - assets/1234.jpg
    - assets/123.jpg
    - assets/user.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/mintora.png"
