name: mintora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  video_player: ^2.9.5
  chewie: ^1.11.3
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.14.3
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.5
  webview_flutter: ^4.13.0
  flutter_downloader: ^1.12.0
  in_app_purchase: ^3.2.3
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mintorav.png
    - assets/12.jpg
    - assets/1234.jpg
    - assets/123.jpg
    - assets/user.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/mintorav.png"

flutter_native_splash:
  color: "#2b2d42"        # Background color for splash (your brand color)
  image: assets/mintorav.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit

